[project]
name = "sbk-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "aiosqlite==0.20.0",
    "bcrypt==4.2.1",
    "fastapi==0.115.6",
    "httpx==0.28.1",
    "pydantic-settings==2.7.0",
    "pydantic[email]==2.10.4",
    "pyjwt==2.10.1",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.20",
    "sqlalchemy[asyncio]==2.0.36",
    "uvicorn[standard]==0.34.0",
]
