"""add_tarea_consumibles_cantidad

Revision ID: 1b3910c6311e
Revises: e3e54b72eabd
Create Date: 2026-08-24 01:19:48.042277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3910c6311e'
down_revision: Union[str, Sequence[str], None] = 'e3e54b72eabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('herramientas', 'stock_actual',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('herramientas', 'stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tarea_consumible_estado', sa.Column('cantidad_asignada', sa.Integer(), nullable=True))
    op.add_column('tarea_consumible_estado', sa.Column('cantidad_devuelta', sa.Integer(), nullable=True))
    op.alter_column('tarea_herramienta_estado', 'cantidad_asignada',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tarea_herramienta_estado', 'cantidad_devuelta',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarea_herramienta_estado', 'cantidad_devuelta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tarea_herramienta_estado', 'cantidad_asignada',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tarea_consumible_estado', 'cantidad_devuelta')
    op.drop_column('tarea_consumible_estado', 'cantidad_asignada')
    op.alter_column('herramientas', 'stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('herramientas', 'stock_actual',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
