"""visitas

Revision ID: 920487cf0ac1
Revises: b7e2c4d9f0a1
Create Date: 2026-09-02 02:14:41.572582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920487cf0ac1'
down_revision: Union[str, Sequence[str], None] = 'b7e2c4d9f0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.Column('personal_id', sa.Uuid(), nullable=True),
    sa.Column('creador_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'EN_PROGRESO', 'FINALIZADA', 'CANCELADA', name='estado_visita'), nullable=False),
    sa.Column('detalles_tecnicos', sa.JSON(), nullable=True),
    sa.Column('incidencias', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creador_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personal_id'], ['personals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitas_cliente_id'), 'visitas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_visitas_creador_id'), 'visitas', ['creador_id'], unique=False)
    op.create_index(op.f('ix_visitas_personal_id'), 'visitas', ['personal_id'], unique=False)
    op.create_index(op.f('ix_visitas_sucursal_id'), 'visitas', ['sucursal_id'], unique=False)
    op.create_table('informes_tecnicos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visita_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('fecha_de_emision', sa.Date(), nullable=True),
    sa.Column('orden_de_compra', sa.String(length=100), nullable=True),
    sa.Column('lugar', sa.String(length=255), nullable=True),
    sa.Column('gen_cliente', sa.String(length=150), nullable=True),
    sa.Column('gen_atencion', sa.String(length=150), nullable=True),
    sa.Column('gen_fecha_de_ejecucion', sa.Date(), nullable=True),
    sa.Column('gen_garantia', sa.String(length=100), nullable=True),
    sa.Column('eq_equipo', sa.String(length=150), nullable=True),
    sa.Column('eq_marca', sa.String(length=150), nullable=True),
    sa.Column('eq_voltaje', sa.String(length=50), nullable=True),
    sa.Column('eq_modelo', sa.String(length=150), nullable=True),
    sa.Column('eq_tipo', sa.String(length=100), nullable=True),
    sa.Column('eq_corriente', sa.String(length=50), nullable=True),
    sa.Column('eq_unidad_de_disparo', sa.String(length=150), nullable=True),
    sa.Column('eq_alimenta', sa.String(length=150), nullable=True),
    sa.Column('eq_categoria', sa.String(length=100), nullable=True),
    sa.Column('cond_camaras_de_extincion_de_arco', sa.String(length=150), nullable=True),
    sa.Column('cond_mecanismo_de_apertura_y_cierre', sa.String(length=150), nullable=True),
    sa.Column('cond_conexiones_de_entrada_y_salida', sa.String(length=150), nullable=True),
    sa.Column('cond_frame_base', sa.String(length=150), nullable=True),
    sa.Column('cond_celda', sa.String(length=150), nullable=True),
    sa.Column('cond_contactos_fijos', sa.String(length=150), nullable=True),
    sa.Column('cond_pruebas_de_accionamiento_mecanico', sa.String(length=150), nullable=True),
    sa.Column('cond_leva_de_disparo', sa.String(length=150), nullable=True),
    sa.Column('cond_frame_tapa', sa.String(length=150), nullable=True),
    sa.Column('cond_barras', sa.String(length=150), nullable=True),
    sa.Column('cond_contactos_moviles', sa.String(length=150), nullable=True),
    sa.Column('cond_cuchillas_secundarias', sa.String(length=150), nullable=True),
    sa.Column('cond_tornilleria_en_general', sa.String(length=150), nullable=True),
    sa.Column('cond_accesorios', sa.String(length=150), nullable=True),
    sa.Column('cond_cables', sa.String(length=150), nullable=True),
    sa.Column('pr_voltaje_vdc', sa.String(length=50), nullable=True),
    sa.Column('pr_a_vs_b', sa.String(length=100), nullable=True),
    sa.Column('pr_b_vs_c', sa.String(length=100), nullable=True),
    sa.Column('pr_c_vs_a', sa.String(length=100), nullable=True),
    sa.Column('pr_abc_vs_tierra', sa.String(length=100), nullable=True),
    sa.Column('pr_entrada_vs_salida', sa.String(length=100), nullable=True),
    sa.Column('pr_salida_vs_entrada', sa.String(length=100), nullable=True),
    sa.Column('pr_unidad_de_disparo_tipo', sa.String(length=150), nullable=True),
    sa.Column('pr_tipo_de_prueba', sa.String(length=150), nullable=True),
    sa.Column('pr_valor_teorico_long_delay', sa.String(length=100), nullable=True),
    sa.Column('pr_valor_dejado', sa.String(length=100), nullable=True),
    sa.Column('pr_simulacion_disparo_corto', sa.String(length=100), nullable=True),
    sa.Column('pr_tierra_ground', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('recomendaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_informes_tecnicos_visita_id'), 'informes_tecnicos', ['visita_id'], unique=True)
    op.alter_column('herramientas', 'stock_actual',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('herramientas', 'stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tarea_consumible_estado', 'cantidad_asignada',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tarea_consumible_estado', 'cantidad_devuelta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tarea_herramienta_estado', 'cantidad_asignada',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tarea_herramienta_estado', 'cantidad_devuelta',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarea_herramienta_estado', 'cantidad_devuelta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tarea_herramienta_estado', 'cantidad_asignada',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tarea_consumible_estado', 'cantidad_devuelta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tarea_consumible_estado', 'cantidad_asignada',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('herramientas', 'stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('herramientas', 'stock_actual',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_informes_tecnicos_visita_id'), table_name='informes_tecnicos')
    op.drop_table('informes_tecnicos')
    op.drop_index(op.f('ix_visitas_sucursal_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_personal_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_creador_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_cliente_id'), table_name='visitas')
    op.drop_table('visitas')
    # ### end Alembic commands ###
