"""add_tarea_estado_and_picking_utilizado

Revision ID: a381722a296f
Revises: aa736d2b6309
Create Date: 2026-08-23 14:06:50.906390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a381722a296f'
down_revision: Union[str, Sequence[str], None] = 'aa736d2b6309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickings', sa.Column('utilizado', sa.Boolean(), nullable=False))
    op.add_column('tareas', sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA', name='estado_tarea'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'estado')
    op.drop_column('pickings', 'utilizado')
    # ### end Alembic commands ###
