"""add_created_at_updated_at_to_tarea_herramienta_estado

Revision ID: aa736d2b6309
Revises: 9154bbf62cc3
Create Date: 2026-08-23 13:46:39.202211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa736d2b6309'
down_revision: Union[str, Sequence[str], None] = '9154bbf62cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarea_consumible_estado', 'estado',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tarea_consumible_estado', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tarea_consumible_estado', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tarea_consumible_estado', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tarea_consumible_estado_estado'), table_name='tarea_consumible_estado')
    op.add_column('tarea_herramienta_estado', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tarea_herramienta_estado', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('tarea_herramienta_estado', 'tarea_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tarea_herramienta_estado', 'herramienta_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tarea_herramienta_estado', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('tarea_herramienta_estado', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tarea_herramienta_estado_estado'), table_name='tarea_herramienta_estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tarea_herramienta_estado_estado'), 'tarea_herramienta_estado', ['estado'], unique=False)
    op.alter_column('tarea_herramienta_estado', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tarea_herramienta_estado', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tarea_herramienta_estado', 'herramienta_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tarea_herramienta_estado', 'tarea_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('tarea_herramienta_estado', 'updated_at')
    op.drop_column('tarea_herramienta_estado', 'created_at')
    op.create_index(op.f('ix_tarea_consumible_estado_estado'), 'tarea_consumible_estado', ['estado'], unique=False)
    op.alter_column('tarea_consumible_estado', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tarea_consumible_estado', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tarea_consumible_estado', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tarea_consumible_estado', 'estado',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'asignado'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
