"""init Postgres

Revision ID: c9c07b578bab
Revises: 
Create Date: 2026-08-22 18:07:32.764528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c07b578bab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rif', sa.String(length=15), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_rif'), 'clientes', ['rif'], unique=True)
    op.create_table('consumibles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('ELECTRICO', 'MECANICO', 'SEGURIDAD', 'LIMPIEZA', 'SOLDADURA', 'PINTURA', 'TUBERIA', 'OTRO', name='tipo_consumible'), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('herramientas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('marca', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.Enum('INALAMBRICO', 'GENERADOR', 'ALMACENAMIENTO', 'MEDICION', 'SEGURIDAD', 'ELECTRICO', 'LOGISTICO', 'MANUAL', name='tipo_herramienta'), nullable=False),
    sa.Column('grupo', sa.Enum('MECANICA_LIGERA', 'POTENCIA_ELECTROPORTATIL', 'MEDICION_DIAGNOSTICO', 'SEGURIDAD_EPP', 'ALMACENAMIENTO_CONSUMIBLES', 'INFRAESTRUCTURA_ELECTRICA', 'LOGISTICA_ASEO', 'SOLDADURA_CORTE_TERMICO', 'NEUMATICA_HIDRAULICA', 'IZAJE_CARGAS', 'PINTURA_ACABADOS', 'TUBERIAS', 'TOPOGRAFIA_NIVELACION', name='grupo_herramienta'), nullable=True),
    sa.Column('combustible', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('imageable_type', sa.String(length=50), nullable=False),
    sa.Column('imageable_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagenes_imageable_id'), 'imagenes', ['imageable_id'], unique=False)
    op.create_index(op.f('ix_imagenes_imageable_type'), 'imagenes', ['imageable_type'], unique=False)
    op.create_table('personals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personals_cedula'), 'personals', ['cedula'], unique=True)
    op.create_table('sucursals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_sucursal', sa.String(length=100), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursals_cliente_id'), 'sucursals', ['cliente_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['personals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cedula'), 'users', ['cedula'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contactos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contactos_sucursal_id'), 'contactos', ['sucursal_id'], unique=False)
    op.create_table('pickings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referencia', sa.String(length=255), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'ASIGNADO', 'EN_PROGRESO', 'COMPLETADO', 'CANCELADO', name='estado_picking'), nullable=False),
    sa.Column('creador_id', sa.Uuid(), nullable=False),
    sa.Column('progreso', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickings_creador_id'), 'pickings', ['creador_id'], unique=False)
    op.create_index(op.f('ix_pickings_referencia'), 'pickings', ['referencia'], unique=False)
    op.create_table('tareas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridad'), nullable=False),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('creador_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creador_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_cliente_id'), 'tareas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_tareas_creador_id'), 'tareas', ['creador_id'], unique=False)
    op.create_index(op.f('ix_tareas_sucursal_id'), 'tareas', ['sucursal_id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tarea_id', sa.Uuid(), nullable=False),
    sa.Column('autor_id', sa.Uuid(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_autor_id'), 'comentarios', ['autor_id'], unique=False)
    op.create_index(op.f('ix_comentarios_tarea_id'), 'comentarios', ['tarea_id'], unique=False)
    op.create_table('pasos_tarea',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tarea_id', sa.Uuid(), nullable=False),
    sa.Column('actividad', sa.Text(), nullable=False),
    sa.Column('metodo', sa.Text(), nullable=True),
    sa.Column('requerimiento', sa.Text(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasos_tarea_tarea_id'), 'pasos_tarea', ['tarea_id'], unique=False)
    op.create_table('picking_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('picking_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'TOMADO', 'NO_DISPONIBLE', 'INNECESARIO', name='estado_picking_item'), nullable=False),
    sa.Column('actualizado_por_id', sa.Uuid(), nullable=True),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
    sa.Column('cantidad_tomada', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('agregado_por_tecnico', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picking_id'], ['pickings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picking_items_picking_id'), 'picking_items', ['picking_id'], unique=False)
    op.create_table('picking_personal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('picking_id', sa.Uuid(), nullable=False),
    sa.Column('personal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['personals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['picking_id'], ['pickings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea_herramienta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', sa.Uuid(), nullable=False),
    sa.Column('herramienta_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['herramienta_id'], ['herramientas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea_personal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', sa.Uuid(), nullable=False),
    sa.Column('personal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['personals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea_picking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', sa.Uuid(), nullable=False),
    sa.Column('picking_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['picking_id'], ['pickings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea_picking')
    op.drop_table('tarea_personal')
    op.drop_table('tarea_herramienta')
    op.drop_table('picking_personal')
    op.drop_index(op.f('ix_picking_items_picking_id'), table_name='picking_items')
    op.drop_table('picking_items')
    op.drop_index(op.f('ix_pasos_tarea_tarea_id'), table_name='pasos_tarea')
    op.drop_table('pasos_tarea')
    op.drop_index(op.f('ix_comentarios_tarea_id'), table_name='comentarios')
    op.drop_index(op.f('ix_comentarios_autor_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_tareas_sucursal_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_creador_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_cliente_id'), table_name='tareas')
    op.drop_table('tareas')
    op.drop_index(op.f('ix_pickings_referencia'), table_name='pickings')
    op.drop_index(op.f('ix_pickings_creador_id'), table_name='pickings')
    op.drop_table('pickings')
    op.drop_index(op.f('ix_contactos_sucursal_id'), table_name='contactos')
    op.drop_table('contactos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cedula'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sucursals_cliente_id'), table_name='sucursals')
    op.drop_table('sucursals')
    op.drop_index(op.f('ix_personals_cedula'), table_name='personals')
    op.drop_table('personals')
    op.drop_index(op.f('ix_imagenes_imageable_type'), table_name='imagenes')
    op.drop_index(op.f('ix_imagenes_imageable_id'), table_name='imagenes')
    op.drop_table('imagenes')
    op.drop_table('herramientas')
    op.drop_table('consumibles')
    op.drop_index(op.f('ix_clientes_rif'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
