"""add_tarea_herramientas_cantidad

Revision ID: e3e54b72eabd
Revises: a381722a296f
Create Date: 2026-08-23 16:30:01.297931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e54b72eabd'
down_revision: Union[str, Sequence[str], None] = 'a381722a296f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('herramientas', sa.Column('stock_actual', sa.Integer(), nullable=True))
    op.add_column('herramientas', sa.Column('stock_minimo', sa.Integer(), nullable=True))
    op.add_column('tarea_herramienta_estado', sa.Column('cantidad_asignada', sa.Integer(), nullable=True))
    op.add_column('tarea_herramienta_estado', sa.Column('cantidad_devuelta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarea_herramienta_estado', 'cantidad_devuelta')
    op.drop_column('tarea_herramienta_estado', 'cantidad_asignada')
    op.drop_column('herramientas', 'stock_minimo')
    op.drop_column('herramientas', 'stock_actual')
    # ### end Alembic commands ###
