"""add cantidad herramientas y consumibles

Revision ID: f9855e965b95
Revises: d745d4f9b22b
Create Date: 2026-08-23 01:06:31.380396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9855e965b95'
down_revision: Union[str, Sequence[str], None] = 'd745d4f9b22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarea_consumible', sa.Column('cantidad', sa.Integer(), nullable=False))
    op.add_column('tarea_herramienta', sa.Column('cantidad', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarea_herramienta', 'cantidad')
    op.drop_column('tarea_consumible', 'cantidad')
    # ### end Alembic commands ###
